In [33]:
print("Hello world")

Hello world


In [34]:
# You can add comments with the # command.
# If you need bigger comments you can use """.

"""
Hello
"""

'\nHello\n'

In [35]:

message = "Hello world!"
print(message)

Hello world!


In [36]:
# Let us do a quick calculation.

initial = 100
ir = 5
years = 7
final = initial*(1+ir/100)**years
print(final)

140.71004226562505


In [37]:
#If you click 'b' you can add a new cell below the current one.
#If you click 'm' you can change the cell to a markdown cell.
#If you click 'y' you can change the cell to a code cell.
#If you click 'd' twice you can delete the cell.


In [38]:
#Now we can check the boolean values.

initial == 100
#This tells us whether initial does have a value of 100.
#Now let us work with this a little bit. Let us change a the value of initial.

print (initial)
initial = 200
print (initial)

#With '=' you can assign a value and with '==' you can check whether the value is true or false.

100
200


In [39]:
#Every file has its own type. You can check the type with the type command.

name = "My name is Diego"
a=2
b=2.

#Once we place a . after the number it becomes a float.

c="2"
d=True
print(type(name))
print(type(a))
print(type(b))
print(type(c))
print(type(d))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


In [40]:
#Now lets see the difference in machine language. Working with floats is difficult.

v1 = 1/51*51
v2=1/49*49

#We know they must be one, but are they?

print(v1)
print(v2)

#They are not the same. This is because the computer has a limited amount of memory to store the numbers.
#This is why we have to be careful when working with floats.

#We can also check whether they are truly one.
print(v1==1)
print(v2==1)

1.0
0.9999999999999999
True
False


In [41]:
#We can set a precision. We can do this with the round command.
print(round(v1)==1)

True


In [42]:
#We can print very nice with the print "f"

pi = 3.1415926535
print(f"({pi:.4f}, {pi:.4})")

#This will print the first four digits of pi.
#The 'f' in .4f is 4 decimals after the coma. If you do not add it is 4 digits in total.

(3.1416, 3.142)


In [43]:
#Let us resume the calculation of interest.

print(f"After {years} years, an initial deposit of {initial} with an interest rate of {ir}% will be {final:.2f}")

#WARNING

#You need to run the cells in order. Remember we changed the 'initial' variable. However we did NOT change the value of final.
#So either redo the calculation of use new variables.

After 7 years, an initial deposit of 200 with an interest rate of 5% will be 140.71


In [44]:
#What if we want to use scientific notation?

large = 10000000000
print(large)
print(f"A lot :{large:g}.")

10000000000
A lot :1e+10.


# LOOPS




for element in list:
<statement1>
<statement2>
...

In [45]:
#Be very much careful with indentation. Python is very strict with this.
#Because we do not have brackets, we use indentation.

for i in [0,1,2,3]:
    print ("Hello im", i)

Hello im 0
Hello im 1
Hello im 2
Hello im 3


In [46]:
#We can use the range command to make this easier.
for i in range(11):
    final = initial*(1+ir/100)**i
    print(f"After {i} years, we would have {final:.2f}€ in the bank.")
    

After 0 years, we would have 200.00€ in the bank.
After 1 years, we would have 210.00€ in the bank.
After 2 years, we would have 220.50€ in the bank.
After 3 years, we would have 231.53€ in the bank.
After 4 years, we would have 243.10€ in the bank.
After 5 years, we would have 255.26€ in the bank.
After 6 years, we would have 268.02€ in the bank.
After 7 years, we would have 281.42€ in the bank.
After 8 years, we would have 295.49€ in the bank.
After 9 years, we would have 310.27€ in the bank.
After 10 years, we would have 325.78€ in the bank.


There are several things to be understood.
1. The 'i' is our iterator variable
2. This variable must have an initial value (here 0) and final value (here 10)
3. The command 'range(N)' creates a list of integers from 0 to N-1. 
4. You can increase the step with the command 'range(a,b+1,s)' where you are starting on 'a', ending exactly on 'b' and with step 's'.
5. You need indentation.

In [47]:
#We can put loops inside loops
for m in range(3):
    for k in range(7):
        print(f"La multiplicación de {m} por {k} es {m*k}")

La multiplicación de 0 por 0 es 0
La multiplicación de 0 por 1 es 0
La multiplicación de 0 por 2 es 0
La multiplicación de 0 por 3 es 0
La multiplicación de 0 por 4 es 0
La multiplicación de 0 por 5 es 0
La multiplicación de 0 por 6 es 0
La multiplicación de 1 por 0 es 0
La multiplicación de 1 por 1 es 1
La multiplicación de 1 por 2 es 2
La multiplicación de 1 por 3 es 3
La multiplicación de 1 por 4 es 4
La multiplicación de 1 por 5 es 5
La multiplicación de 1 por 6 es 6
La multiplicación de 2 por 0 es 0
La multiplicación de 2 por 1 es 2
La multiplicación de 2 por 2 es 4
La multiplicación de 2 por 3 es 6
La multiplicación de 2 por 4 es 8
La multiplicación de 2 por 5 es 10
La multiplicación de 2 por 6 es 12



Let us do a little exercise

Write a loop that calculates the sum of all integers from 1 to N ad print out the final result.

In [48]:
N = 100
result=0
for i in range(1,N+1,1):
    result=result+i
print(f"The final result is {result}")

The final result is 5050


Now let us doo WHILE LOOPS


In [49]:
#Let us do a while loop
i=0
initial=100
ir=5
while i<11: #the Boolean condition controlling the loop
    final=initial*(1+ir/100)**i
    print(f"After {i} years, we would have {final:.2f}€ in the bank.")
    i+=1  #This is the increment of the loop.

After 0 years, we would have 100.00€ in the bank.
After 1 years, we would have 105.00€ in the bank.
After 2 years, we would have 110.25€ in the bank.
After 3 years, we would have 115.76€ in the bank.
After 4 years, we would have 121.55€ in the bank.
After 5 years, we would have 127.63€ in the bank.
After 6 years, we would have 134.01€ in the bank.
After 7 years, we would have 140.71€ in the bank.
After 8 years, we would have 147.75€ in the bank.
After 9 years, we would have 155.13€ in the bank.
After 10 years, we would have 162.89€ in the bank.


In [50]:
#Let us redo the exercise with the while loop.
i=0
result=0
N=100
while i<N+1:
    result=result+i
    i+=1
print(f"The final result is {result}")

The final result is 5050


Boolean Logic:

- AND : only true when they are both true
- OR: true when one of them is true
- NOT: ....

# Functions

In [51]:
#What if we do not want to copy and paste everytime. We can use functions.

#For that we use the 'def' command.

"""
def function_name(argument1, argument2):
    local_variable = argument1 + argument2
    return local_variable
    
"""

'\ndef function_name(argument1, argument2):\n    local_variable = argument1 + argument2\n    return local_variable\n    \n'

In [52]:
#Let us do the interest function

def final_amount(initial, years):
    final = initial*(1+ir/100)**years
    return final

#When you run this function in jupyter, you will not see anything. You need to call the function.

In [53]:
#However after you call, you will see the result.

final_amount(100,7)

140.71004226562505

In [54]:
#Another thing to take into account is DOCUMENTING YOUR FUNCTION.
#How do we do this?

#We need to use the """ command.

def final_amount(initial, years):
    """

    Args:
        initial (float): The initial value of the deposit.
        years (integer): The amount of years it will be deposited.
    
    Returns:
    
        final: The final amount of the deposit after the years.
    
    """
    final = initial*(1+ir/100)**years
    return final
    

In [55]:
#Let us do the same function as before

def suma(N):
    """
    Args:
        N (integer): The number until which we want to sum.
    
    Returns:
    
        result: The final result of the sum.
    
    """
    result=0
    for i in range(1,N+1,1):
        result=result+i
    return result

In [56]:
#Remember, variables INSIDE a function python does not know what they are. They are local variables.
#If you want to use them outside the function, you need to return them.


#You can change the order of the function if it needs multiple parameters ONLY IF YOU REMEMBER THE VARIABLE NAME.

In [57]:
#Let us do a little exercise. 
#Define a function that returns the area and the perimeter of a given circle's radius.
from math import pi
print (pi)

def perimetro_area(r):
    """
    Args:
        r (float): The radius of the circle.
    
    Returns:
    
        perimetro: The perimeter of the circle.
        area: The area of the circle.
    
    """
    perimetro = 2*pi*r
    area = pi*r**2
    return perimetro, area

3.141592653589793


In [58]:
#Let us check whether the perimeter and area are correct.
#Remember the ORDER it exports the variables.

perimetro, area = perimetro_area(5)

print(f"The perimeter of the circle is {perimetro:.2f} and the area is {area:.2f}")

The perimeter of the circle is 31.42 and the area is 78.54


In [59]:
#Functions dont need to have a return value. They can be void functions.

def silly(input):
    print(input)

silly("hello")

hello


# If statements


if condition:

    < code that executes if the condition is true>

elif (in order and you can concatenate conditions)

else (you dont need else)
    
    < code outside the if statement>

In [60]:
#Let us do a change to the bank function.
#We will change whether the interest rate is 5, 6 or 8 depending on the initial deposit.
#We will be using if, elif and else

def final_amount(initial, years):
    
    if initial <= 1000:
        ir = 5
    elif initial <= 10000:
        ir = 6
    else:
        ir = 8
    
    final_amount=initial*(1+ir/100)**years
    
    #I've added the ir to the return so we can check the interest rate.
    
    return final_amount, ir


In [61]:
print(final_amount(999,7))
print(final_amount(1000,7))
print(final_amount(1001,7))
print("--------")
print(final_amount(9999,7))
print(final_amount(10000,7))
print(final_amount(10001,7))

(1405.6933222335942, 5)
(1407.1004226562504, 5)
(1505.133889250352, 6)
--------
(15034.798959654614, 6)
(15036.302589913606, 6)
(17139.95651206399, 8)


# Lists

We will be using [element0, element1,...,elementfinal]

Python indexes start at 0

In [62]:
list1=[1,2,3,4,5,6,7,8,9,10]
list2=[pi,'hello',4]
print(list1)
print(list2)



[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[3.141592653589793, 'hello', 4]


In [63]:
#you can create an empty list and then you can start filling it.

empty =[]
len(empty)

0

In [64]:
#If we want to add a single element to the end
my_first_list1=[1,2,3,4,5,6,7,8,9,10]

my_first_list1.append(11)
print(my_first_list1)

#If we want to add more than one element at the end

my_first_list1= my_first_list1 + [12,13]
print(my_first_list1)

#To delete a specific element of the list
del(my_first_list1[0])
print(my_first_list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]


In [65]:
#Let us do the bank but now all the data has to be stored.


def final_list(initial, years):
    
    list=[]
    ir=5
    
    for i in range(years+1):
        final_amount=initial*(1+ir/100)**i
        list.append(final_amount)
    
    return final_amount, list
    
print(final_list(100,3))

(115.76250000000002, [100.0, 105.0, 110.25, 115.76250000000002])


In [66]:
#Be careful with this. Graphical example is better.
L1=[1,2,3]
L2=L1

#THIS MAKES PYTHON REMEMBER THE LIST, even if you change L1 in another code, see below.

In [67]:
L1[-1]="!"

#we changed L1, but L2 also changed.
print(L2)

[1, 2, '!']


In [68]:
#To avoid this we can copy the list. We can do this with the copy command. 
L1=[1,2,3]
L3 = L1.copy()
L1[-1]="!"
print(L3)

[1, 2, 3]


In [69]:
#We can also do lists of lists.
nest=[L1,L2,L3]
print(nest)

#This is like a matrix, we first choose the element 0 of nest and of that list, element 1.
nest[0][1]


[[1, 2, '!'], [1, 2, '!'], [1, 2, 3]]


2

In [70]:
#We can also do list slicing. This is very useful.
print(my_first_list1)

#The : is in steps of 2. It is the same syntax as in the range command.
#The len() command is to know the length of the list.

print(my_first_list1[0:len(L2):2])

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
[2, 4]


# -------------------- NUMPY INTRODUCTION --------------------------

Numpy is compatible with numba, a program that optimises your python program.

Numpy is extremely used, so every problem you have you can find it on google.

##### Whenever you want to use a library, you need to IMPORT it

It is recommended that you import at the start.

Whenever you need to call a library, you can use 'as' command, because if not you would need to write numpy. everytime

It should look like 'import numpy as np'

It is a bad idea to use 'from numpy import *'. This imports every function of numpy and you dont need to use numpy. everytime. However this is a bad idea because now you dont know which library are you using, if using more than one library it can overlap, etc..


In [83]:
#An example of importing things
import os
import scipy
import numpy as np
import matplotlib as plt


In [84]:
#An example of using numpy
root = np.sqrt(2)
print(root)

1.4142135623730951


We use numpy primary to use vectors and matrices.

We can create a vector with the np.array command.



In [85]:
vec=np.array([1,2,3]) #A vector with 3 elements
A=np.array([[1,2,3],[4,5,6],[7,8,9]]) #A 3x3 matrix
B=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]]) #A 3x2x2 tensor	

In [86]:
#Now lets see them
print('vec as a vector:',vec)
print('A as a matrix:',A)  
print('B as a tensor:',B)

vec as a vector: [1 2 3]
A as a matrix: [[1 2 3]
 [4 5 6]
 [7 8 9]]
B as a tensor: [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [87]:
#You should know the shape of the array, even though sometimes it can be confusing.
#We can check the shape of the array with the shape command.

print(vec.shape)
print(A.shape)
print(B.shape)

(3,)
(3, 3)
(3, 2, 2)


In [88]:
#You can also use the .size command, giving you the total number of elements in the array.
print(vec.size)
print(A.size)
print(B.size)
#You can also use np.shape and np.size

3
9
12


#### What is the advantage of using an np.array?

The numbers inside must be of the same type so this eliminates some problems.

They are much more efficiently made.


In [89]:
#If we do the comand .dtype we can see the type of the array.

print(vec.dtype)
print(A.dtype)
print(B.dtype)


int32
int32
int32


In [90]:
#If we dont put anything it will assume it is an integer.
#But what if we want to specify the type of the array?

M1=np.array([[1,2],[3,4]], dtype=int)
M2=np.array([[1,2],[3,4]], dtype=complex)

print(M1.dtype)
print(M2.dtype)

int32
complex128


In [91]:
#We can also create RANGE arrays with arange command.

v=np.arange(0,10,1)
print(v)

v=np.arange(-1,1,0.1)
print(v)

#Remember 2 things: The last element is not included and the step is not included.
#And the precision problems with floats. 0 is not -2.220446049250313e-16.

[0 1 2 3 4 5 6 7 8 9]
[-1.00000000e+00 -9.00000000e-01 -8.00000000e-01 -7.00000000e-01
 -6.00000000e-01 -5.00000000e-01 -4.00000000e-01 -3.00000000e-01
 -2.00000000e-01 -1.00000000e-01 -2.22044605e-16  1.00000000e-01
  2.00000000e-01  3.00000000e-01  4.00000000e-01  5.00000000e-01
  6.00000000e-01  7.00000000e-01  8.00000000e-01  9.00000000e-01]


In [92]:
#If you use .linspace(a,b,c) you can create an array with c elements between a and b WITH 'b' INCLUDED.
v=np.linspace(0,10,11)
print(v)

v=np.linspace(-1,1,21)
print(v)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[-1.  -0.9 -0.8 -0.7 -0.6 -0.5 -0.4 -0.3 -0.2 -0.1  0.   0.1  0.2  0.3
  0.4  0.5  0.6  0.7  0.8  0.9  1. ]


In [93]:
#We can also create arrays of zeros and ones.

Z1=np.zeros(2, dtype=int)
Z2=np.zeros((3,3), dtype=float)
O1=np.ones(2, dtype=int)
O2=np.ones((3,3), dtype=float)


In [94]:
#We can also use random numbers. We can use the random command.

Identity=np.eye(3) #This creates a 3x3 identity matrix
Diagonal=np.diag([1,2,3,4,5,6,7,8,9,10]) #This creates a matrix with the input list in the diagonal
Random=np.random.rand(3,3) #Creates a 3x3 matrix with random numbers between 0 and 1

print(Identity)
print(Diagonal)
print(Random)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 1  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0]
 [ 0  0  0  4  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0]
 [ 0  0  0  0  0  0  7  0  0  0]
 [ 0  0  0  0  0  0  0  8  0  0]
 [ 0  0  0  0  0  0  0  0  9  0]
 [ 0  0  0  0  0  0  0  0  0 10]]
[[0.6950836  0.07297347 0.66382189]
 [0.78715282 0.9702961  0.41175432]
 [0.13381779 0.28107549 0.80274925]]


# ------------------- JOEL PROTEUS-----------------

To enter Joel

ssh cphys-username@joel.ugr.es

It will ask you for your password, and even though it appears you are not writing you are indeed writing.


You will need to navigate once inside joel.

You will need to use google.

### The commands are these:

- 'ls' tells you the bins you have
- 'cd _foldername_' you get inside the bin. If you write '..' you will exit the bin you are. You would want to get inside 'COMPARTIDO'
- 'mkdir' creates a folder, it makes a directory.
- 'ls -lh'
- 'pwd' tells you the directory you are in. It is pretty useful for the next step.
- 'scp' means copy TO server. You will need to put the name of the file or the path, then your name then the directory. 
    - For example. 'scp [space] _NameOfFile/Path_ [space] _YourName_:/_FolderInJoel_. 
- 'scp' means to copy FROM server. 
    - For example. 'scp [space] _YourName_ :/ _PathofArchivo_ [space] _FolderInYourComputer


# -------GITHUB AND GIT-------------


### We will be seeing how to connect to git and stuff.

Filipa's github account "fcrperes".

We now will be using the terminal this time

### Commands:

- 'git' ALWAYS used.
- 'git clone' makes you clone a certain repository to your computer.
    - For example 'git clone _PathFromGithub_'
- 'git add' makes you add the file to the path you just select.
    - 